### ISSUE TITLE
Display List of Parties

### ISSUE THREAD

**Issue by tomnunn** [crsanghani/street-party#27]
As a user,
So I can see a list of parties,
I would like to be able to view a list of all parties

### Tasks
- [x] Create Parties Template (Parties.html)
- [ ] Feature Test
- [x] Add Parties Route (lib/routes.js)
- [x] Add Meteor Subscribe and Publish functions (server/publish.js and client/parties/parties.js)
- [x] Display Parties in /parties route
- [x] Modify Styling of .party class
